version: 0.2

phases:
  install:
      commands:
      - echo "Starting installs . . ."
      - sudo apt-get update -y
      - pip install --upgrade pip
      # install awscli
      - pip install awscli --upgrade --user
      # mysql client
      - sudo apt-get install mysql-client -y
      - dotnet tool install dotnet-reportgenerator-globaltool --version 4.3.6
  build:
    commands:
      - echo "Starting builds . . ."