version: 0.2

phases:
  install:
      runtime-versions:
        dotnet: 3.0
      commands:
      - echo "Starting installs . . ."
      # Install pip
      - sudo apt-get install python-pip
      - sudo apt-get update -y
      - npm install
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - pip install --upgrade pip
      # install awscli
      - pip install awscli --upgrade --user
      # mysql client
      - sudo apt-get install mysql-client -y
  build:
    commands:
      - echo "Starting builds . . ."