version: 0.2

phases:
  install:
      runtime-versions:
        dotnet: 3.0
      commands:
      - echo "Starting installs . . ."
      - sudo apt-get install update -y
      - sudo apt-get install python-pip
      - pip install --upgrade pip
      # install awscli
      - pip install awscli --upgrade --user
      # mysql client
      - sudo apt-get install mysql-client -y

  build:
    commands:
      - echo "Starting builds . . ."